name: Run static code analysis

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install libraries
        run: yarn

      - name: Lint
        run: yarn lint
